"""empty message

Revision ID: 028d962c13b7
Revises: 6558f8b80d96
Create Date: 2021-03-05 20:44:25.942047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028d962c13b7'
down_revision = '6558f8b80d96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('coverpic', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'coverpic')
    # ### end Alembic commands ###
