"""empty message

Revision ID: 2906d27c009a
Revises: 6b4e2b1ac48b
Create Date: 2021-03-06 00:03:18.279797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2906d27c009a'
down_revision = '6b4e2b1ac48b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'director')
    op.drop_column('movie', 'coverpic')
    op.drop_column('movie', 'cast')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('cast', sa.VARCHAR(length=500), nullable=True))
    op.add_column('movie', sa.Column('coverpic', sa.VARCHAR(length=500), nullable=True))
    op.add_column('movie', sa.Column('director', sa.VARCHAR(length=500), nullable=True))
    # ### end Alembic commands ###
