"""empty message

Revision ID: 2e49965cf4c8
Revises: 459042becb8e
Create Date: 2021-03-11 16:57:16.945640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e49965cf4c8'
down_revision = '459042becb8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('year', sa.Integer(), nullable=True))
    op.drop_column('movie', 'cast')
    op.drop_column('movie', 'coverpic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('coverpic', sa.VARCHAR(length=500), nullable=True))
    op.add_column('movie', sa.Column('cast', sa.VARCHAR(length=500), nullable=True))
    op.drop_column('movie', 'year')
    # ### end Alembic commands ###
