"""empty message

Revision ID: 459042becb8e
Revises: dcd7b0b201e5
Create Date: 2021-03-11 16:56:35.941796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '459042becb8e'
down_revision = 'dcd7b0b201e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('year', sa.Integer(), nullable=True))
    op.drop_column('movie', 'coverpic')
    op.drop_column('movie', 'cast')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('cast', sa.VARCHAR(length=500), nullable=True))
    op.add_column('movie', sa.Column('coverpic', sa.VARCHAR(length=500), nullable=True))
    op.drop_column('movie', 'year')
    # ### end Alembic commands ###
