"""empty message

Revision ID: 49dae4b747e8
Revises: 028d962c13b7
Create Date: 2021-03-05 21:03:27.473080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49dae4b747e8'
down_revision = '028d962c13b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('director', sa.String(length=500), nullable=True))
    op.drop_column('movie', 'cast')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('cast', sa.VARCHAR(length=500), nullable=True))
    op.drop_column('movie', 'director')
    # ### end Alembic commands ###
