"""empty message

Revision ID: 6558f8b80d96
Revises: fa067ccdcb98
Create Date: 2021-03-05 18:53:12.844879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6558f8b80d96'
down_revision = 'fa067ccdcb98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('cast', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'cast')
    # ### end Alembic commands ###
