"""empty message

Revision ID: 6b4e2b1ac48b
Revises: 49dae4b747e8
Create Date: 2021-03-06 00:02:45.194820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b4e2b1ac48b'
down_revision = '49dae4b747e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'cast')
    op.drop_column('movie', 'director')
    op.drop_column('movie', 'coverpic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('coverpic', sa.VARCHAR(length=500), nullable=True))
    op.add_column('movie', sa.Column('director', sa.VARCHAR(length=500), nullable=True))
    op.add_column('movie', sa.Column('cast', sa.VARCHAR(length=500), nullable=True))
    # ### end Alembic commands ###
