"""empty message

Revision ID: dcd7b0b201e5
Revises: 2906d27c009a
Create Date: 2021-03-11 15:36:30.689007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcd7b0b201e5'
down_revision = '2906d27c009a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('movie_poster', sa.String(length=100), nullable=True))
    op.drop_column('movie', 'cast')
    op.drop_column('movie', 'coverpic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('coverpic', sa.VARCHAR(length=500), nullable=True))
    op.add_column('movie', sa.Column('cast', sa.VARCHAR(length=500), nullable=True))
    op.drop_column('movie', 'movie_poster')
    # ### end Alembic commands ###
